_target_: standard_featurization.features.factory.ProteinFeaturiser
representation: CA
scalar_node_features:
  # - amino_acid_one_hot
  - dihedrals
vector_node_features: ["orientation"]
edge_types:
  - knn_30
scalar_edge_features:
  - edge_distance
vector_edge_features: ["edge_vectors"]
